---
title: "Relatório"
author: "Pedro Guimarães"
format:
  html:
    toc: true
    code-copy: true
embed-resources: true
editor: source
execute:
  warning: false
  embed-resources: true
toc-title: "Relatório"
lang: pt
---

```{r}
#| echo: false
library(tidyverse)
library(ggthemes)
library(plotly)
library(skimr)
library(gt)
```

```{r}
#| echo: false
setwd("C:/Users/Pedro/Minhas coisas/Meus documentos/2026/UFLA/ges139/projeto/EDA_population_and_GDP/dados")

df <- readRDS("tabela_com_3.rds")

Anos <- names(df)
pa <- as.numeric(c(df[3, ], df[2, ], df[1, ]))
nom <- c(rep("Média Geral", 4), rep("Países Ricos", 4),
         rep("Países Pobres", 4))
df.2 <- data.frame(rep(Anos, 3), nom, pa)
df.2 <- rename(df.2,
               Ano = "rep.Anos..3.",
               Tipo = "nom",
               Taxa = "pa")
df.2 <- mutate(df.2, across(-Taxa, as.factor),
               across(Taxa, as.numeric))

ggplot(
  data = df.2,
  mapping = aes(x = Ano, y = Taxa, group = Tipo, colour = Tipo)
) + 
  geom_line(stat = "identity", linewidth = 1.5
            ) +
  labs(
    title = "Taxa de fertilidade para países ricos e pobres de 2010 à 2025",
    x = "Ano da pesquisa", y = "Taxa de Fertilidade",
    color = "Classificação do país"
  ) +
  scale_colour_manual(
    values = c( "orange", "steelblue", "darkred")
  ) -> linha
```

```{r}
#| echo: false
setwd("C:/Users/Pedro/Minhas coisas/Meus documentos/2026/UFLA/ges139/projeto/EDA_population_and_GDP/dados")
tabela <- readRDS("tabelafinal.rds")

tabela <- tabela[, -4:-6]
t.tipo <- c(rep("Países Ricos", 28),
             rep("Países Emergentes", 28),
             rep("Países Pobres", 28))

t4 <- tabela |>
  filter(Year == "2025") |>
  arrange(desc(PIB))
t4.n <- data.frame(t4, t.tipo)
t4.n <- rename(t4.n,
               Taxa = "Life.expectancy",
               Tipo = "t.tipo")
t4.n <- mutate( t4.n,
                across(Tipo, as.factor),
                across(Taxa, as.numeric),
                Tipo = fct_relevel(Tipo,
                                   c("Países Ricos",
                                     "Países Emergentes",
                                     "Países Pobres")))

t1 <- tabela |>
  filter(Year == "2010") |>
  arrange(desc(PIB))
t1.n <- data.frame(t1, t.tipo)
t1.n <- rename(t1.n,
               Taxa = "Life.expectancy",
               Tipo = "t.tipo")
t1.n <- mutate( t1.n,
                across(Tipo, as.factor),
                across(Taxa, as.numeric),
                Tipo = fct_relevel(Tipo,
                                   c("Países Ricos",
                                     "Países Emergentes",
                                     "Países Pobres")))

ggplot(t4.n,
       aes(x = Tipo, y = Taxa, colour = Tipo)
) +
  geom_boxplot(varwidth = TRUE) +
  labs(
    title = "Expectativa de vida para países Ricos, Emergentes e Pobres em 2025",
    x = "Tipo de País", y = "Expectativa de vida"
  ) +
  scale_colour_manual(
    values = c("darkgreen", "steelblue", "darkred")
  ) -> box.4

ggplot(t1.n,
       aes(x = Tipo, y = Taxa, colour = Tipo)
) +
  geom_boxplot(varwidth = TRUE) +
  labs(
    title = "Expectativa de vida para países Ricos, Emergentes e Pobres em 2010",
    x = "Tipo de País", y = "Expectativa de vida"
  ) +
  scale_colour_manual(
    values = c("darkgreen", "steelblue", "darkred")
  ) -> box.1
```

##

###

###

##

```{r}
#| echo: false
ggplotly(linha)
```

##

###

```{r}
#| echo: false
ggplotly(box.1)
```

###

```{r}
#| echo: false
ggplotly(box.4)
```
